name: Rubocop

on: [push]

jobs:
  lint:
    name: 'Lint'
    timeout-minutes: 10
    runs-on: ubuntu-latest

    container:
      image: ruby:3.1.3

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: /usr/local/bundle
          key: ${{ runner.os }}-gem-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gem-

      - name: Install dependencies
        run: |
          gem install bundler:2.3.18
          bundle install --local

      - name: Rubocop
        run: bin/rubocop
